sudo: false
language: php
php:
    - 5.6
    - 7.0
    - 7.2

before_script:
  - composer self-update
  - composer install --no-interaction --prefer-dist --dev

script:
  - vendor/bin/phpcs --standard=PSR1 src/ tests/
  - vendor/bin/phpunit
